added composer 2 support
exozet/docker-php-fpm pull request #173
Opened 2020-12-08 12:14 UTC by niepi

- installs both versions of composer
- upgrades composer 1 to 1.10.17
- installs composer 2 at 2.0.7
- ENV var COMPOSER_MAYOR_VERION decides with version is used, defaults to version 1

2020-12-08 13:42 UTC, OskarStark requested changes

2020-12-08 13:42 UTC, OskarStark commented on 7.4/Dockerfile
> +ENV COMPOSER_MAYOR_VERION=1 \
```suggestion
ENV COMPOSER_VERSION=1 \
```

2020-12-08 13:42 UTC, OskarStark commented on 7.4/Dockerfile-alpine
> +ENV COMPOSER_MAYOR_VERION=1 \
```suggestion
ENV COMPOSER_VERSION=1 \
```

2020-12-08 13:42 UTC, OskarStark commented on composer.sh
> +if [ -n "$COMPOSER_MAYOR_VERION" ]
```suggestion
if [ -n "$COMPOSER_VERSION" ]
```

2020-12-08 13:42 UTC, OskarStark commented on composer.sh
> +    /usr/local/bin/composer$COMPOSER_MAYOR_VERION "$@"
```suggestion
    /usr/local/bin/composer$COMPOSER_VERSION "$@"
```

2020-12-08 13:42 UTC, OskarStark commented on composer.sh
> +
```suggestion
```

2020-12-08 14:29 UTC, niepi reviewed
Apply suggestions from code review

2020-12-08 18:20 UTC, llupa commented
When will this be merged?

2020-12-09 06:17 UTC, OskarStark commented
Thanks @niepi I am going to merge this.

@llupa can you please report back if everything works fine?

Afterwards please backport this feature to the other branches please. Thanks

2020-12-09 06:17 UTC, merged

2020-12-09 06:44 UTC, niepi commented
I will create a new PR to add documentation